version: '2'

services:

  frontier:
    image: squirrel
    container_name: frontier
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - SEED_FILE=/var/squirrel/data/seeds.txt
      - RDB_HOST_NAME=rethinkdb
      - RDB_PORT=28015
#    networks:
#      - squirrel
    volumes:
      - ./scenarios/1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.FrontierComponent

  rethinkdb:
    image: rethinkdb:2.3.5
#    networks:
#      - squirrel
#    volumes:
#      - ./scenarios/1/rethinkdb:/data

  # message bus
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    hostname: rabbit
#    networks:
#      - squirrel

  worker1:
    image: squirrel
    container_name: worker1
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - OUTPUT_FOLDER=/var/squirrel/data
#    networks:
#      - squirrel
    volumes:
        - ./scenarios/1/worker1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  SimulationNodeA:
    image: squirrel
    container_name: NodeA
    environment:
      - RESOURCE_MODEL=/var/squirrel/data/nodeA.ttl
      - RESOURCE_MODEL_LANG=N3
      - PORT=80
      - DUMP_FILE_NAME=dump.gz
      - USE_DEREF=true
#    networks:
#      - squirrel
    volumes:
        - ./scenarios/1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.SimpleHttpServerComponent

  SimulationNodeB:
    image: squirrel
    container_name: NodeB
    environment:
      - RESOURCE_MODEL=/var/squirrel/data/nodeB.ttl
      - RESOURCE_MODEL_LANG=N3
      - PORT=80
      - USE_DEREF=true
#    networks:
#      - squirrel
    volumes:
        - ./scenarios/1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.SimpleHttpServerComponent

  SimulationNodeC:
    image: squirrel
    container_name: NodeC
    environment:
      - RESOURCE_MODEL=/var/squirrel/data/nodeC.ttl
      - RESOURCE_MODEL_LANG=N3
      - PORT=80
      - DUMP_FILE_NAME=dump.gz
      - USE_DEREF=false
#    networks:
#      - squirrel
    volumes:
        - ./scenarios/1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.SimpleHttpServerComponent

#networks:
#  squirrel:
#    external:
#      name: squirrel
