version: "2"

services:
  rethinkdb:
    image: rethinkdb:2.3.6
    volumes:
      - ./data/rethinkdb:/data

  # message bus
  rabbit:
    image: rabbitmq:management

  frontier:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      SEED_FILE: /var/squirrel/data/seeds.txt
      RDB_HOST_NAME: rethinkdb
      RDB_PORT: 28015
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
      COMMUNICATION_WITH_WEBSERVICE: "true"
    volumes:
      - ./data/frontier:/var/squirrel/data
      - ./seeds.txt:/var/squirrel/data/seeds.txt:ro
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.FrontierComponent

  web:
    image: java:latest
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - ../web/Squirrel-Webservice/target:/etc/store
    command: java -jar /etc/store/SPRINGWebSquirrelJar-0.3.0.jar

  worker1:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
    volumes:
        - ./data/worker1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker2:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
    volumes:
        - ./data/worker2:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker3:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
    volumes:
        - ./data/worker3:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent
