version: "2"

services:
  rethinkdb:
    image: rethinkdb:2.3.6
    volumes:
      - ./data/rethinkdb:/data

  # message bus
  rabbit:
    image: rabbitmq:management

  sparqlHost:
      image: stain/jena-fuseki
      container_name: sparqlHost
      ports:
        - "3030:3030"
      volumes:
        - ./data/sparqlHost:/fuseki
      environment:
        - ADMIN_PASSWORD=pw123
        - JVM_ARGS=-Xmx2g

  frontier:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      SEED_FILE: /var/squirrel/data/seeds.txt
      RDB_HOST_NAME: rethinkdb
      RDB_PORT: 28015
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
      COMMUNICATION_WITH_WEBSERVICE: "false"
    volumes:
      - ./data/frontier:/var/squirrel/data
      - ./seeds.txt:/var/squirrel/data/seeds.txt:ro
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.FrontierComponent

  worker1:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
      SPARQL_HOST_NAME: sparqlHost
      SPARQL_HOST_PORT: 3030
      RDB_HOST_NAME: rethinkdb
      RDB_PORT: 28015
    volumes:
        - ./data/worker1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker2:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
      DEDUPLICATION_ACTIVE: "true"
      SPARQL_HOST_NAME: sparqlHost
      SPARQL_HOST_PORT: 3030
      RDB_HOST_NAME: rethinkdb
      RDB_PORT: 28015
    volumes:
        - ./data/worker2:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker3:
    image: squirrel
    environment:
      HOBBIT_RABBIT_HOST: rabbit
      OUTPUT_FOLDER: /var/squirrel/data
      SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
      DEDUPLICATION_ACTIVE: "true"
      SPARQL_HOST_NAME: sparqlHost
      SPARQL_HOST_PORT: 3030
      RDB_HOST_NAME: rethinkdb
      RDB_PORT: 28015
    volumes:
        - ./data/worker3:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  deduplicator:
     image: squirrel
     container_name: deduplicator
     environment:
       DEDUPLICATION_ACTIVE: "true"
       HOBBIT_RABBIT_HOST: rabbit
       RDB_HOST_NAME: rethinkdb
       RDB_PORT: 28015
       SPARQL_HOST_NAME: sparqlHost
       SPARQL_HOST_PORT: 3030
       OUTPUT_FOLDER: /var/squirrel/data
       SERVICE_PRECONDITION: "rethinkdb:28015 rabbit:5672"
     volumes:
          - ./data/deduplicator:/var/squirrel/data
     command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.DeduplicatorComponent

